### ISSUE TITLE
de waarde voor sectie 2 wordt verderop in je script overschreven

### ISSUE THREAD

**Issue by Theo-denBlanken** [Pisav/parallax#1]
````
const corrSection4 = (gescrolled) => {
	sectie2.style.backgroundPositionY = -gescrolled/3 + "px";
}
const corrSection6 = (gescrolled) => {
	sectie2.style.backgroundPositionY = 400 -gescrolled/2 + "px";
}
````
in dit stuk van je script overschrijf je de stijl van sectie 2 telkens weer.....
Je moet daar natuurlijk met sectie 4 en sectie 6 aan de slag in plaats van jouw inspanningen in sectie2 teniet gaan doen.

**Comment by Pisav** [comment]
ohja, domme fout.
als het goed is doet hij het nu wel.
ik zal de github updaten.

mvg,

 Vadim
________________________________
Van: Theo den Blanken <notifications@github.com>
Verzonden: woensdag 30 oktober 2019 10:20
Aan: Pisav/parallax <parallax@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [Pisav/parallax] de waarde voor sectie 2 wordt verderop in je script overschreven (#1)


const corrSection4 = (gescrolled) => {
        sectie2.style.backgroundPositionY = -gescrolled/3 + "px";
}
const corrSection6 = (gescrolled) => {
        sectie2.style.backgroundPositionY = 400 -gescrolled/2 + "px";
}


in dit stuk van je script overschrijf je de stijl van sectie 2 telkens weer.....
Je moet daar natuurlijk met sectie 4 en sectie 6 aan de slag in plaats van jouw inspanningen in sectie2 teniet gaan doen.
